[general]
connection = "server=localhost; database=cardmanagement; username=root; password=12345"
output = "SqlHydraTypesProvider.fs"
reader_type = "Microsoft.Data.SqlClient.SqlDataReader"
namespace = "CardManagement.Data"
cli_mutable = true
[sqlhydra_query_integration]
provider_db_type_attributes = true
table_declarations = true
[readers]
reader_type = "Npgsql.NpgsqlDataReader"
[filters]
include = []
exclude = []
