version: "3.9"

services:
  ps:
    image: postgres:15.3
    container_name: ps
    restart: always
    ports:
      - 5432:5432
    env_file:
        - .env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data